version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: gtfs-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: gtfs_db
      POSTGRES_USER: ztp_user
      POSTGRES_PASSWORD: ztp_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: