spring.application.name=to-ztp

ztp.gtfs.url=https://gtfs.ztp.krakow.pl
ztp.gtfs.statics.file=GTFS_KRK.zip
ztp.gtfs.statics.data-dir=data
ztp.gtfs.check-interval-ms=3600000

spring.datasource.url=jdbc:postgresql://localhost:5432/gtfs_db?reWriteBatchedInserts=true
spring.datasource.username=ztp_user
spring.datasource.password=ztp_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.properties.hibernate.jdbc.batch_size=500
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true