spring.application.name=to-ztp

ztp.gtfs.url=https://gtfs.ztp.krakow.pl
ztp.gtfs.statics.file=GTFS_KRK.zip
ztp.gtfs.statics.data-dir=data
ztp.gtfs.statics.filenames.routes=routes.txt
ztp.gtfs.statics.filenames.stops=stops.txt
ztp.gtfs.statics.filenames.calendar=calendar.txt
ztp.gtfs.statics.filenames.calendar-dates=calendar_dates.txt
ztp.gtfs.statics.filenames.trips=trips.txt
ztp.gtfs.statics.filenames.stop-times=stop_times.txt
ztp.gtfs.check-interval-ms=90000
ztp.gtfs.jdbc-batch.trips=5000
ztp.gtfs.jdbc-batch.stop-times=5000

spring.datasource.url=jdbc:postgresql://localhost:5432/gtfs_db?reWriteBatchedInserts=true
spring.datasource.username=ztp_user
spring.datasource.password=ztp_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.batch_size=500
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

spring.main.bannerMode=off
logging.pattern.console=

ztp.mcp.stops.default-size=200
ztp.mcp.stops.max-size=1000